# Generated by Django 2.0.5 on 2018-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
